version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
  deployShinyio:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT_STG $SSH_USER@$SSH_HOST_STG
  deploystg:
    docker:
      - image: boxboat/kubectl:1.15.12
    steps:
      - run: |
          export PWD=$(pwd)
          echo $OKTETO_SECERT | base64 -d > "$PWD/config"
          wget -O ~/deployment.yaml "$STG_GIST_URL"
          sed -i -e "s/{{BRA_NAME}}/$CIRCLE_BRANCH/; s/{{BRA_NAME}}/$CIRCLE_SHA1/" ~/deployment.yaml
          kubectl --kubeconfig="$PWD/config" apply -f ~/deployment.yaml
workflows:
  version: 2
  chk-on-stg:
    jobs:
      - deploystg:
          filters:
            branches:
              only: /^de.*/
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - deployShinyio:
          filters:
            branches:
              only: master
