version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
  deployShinyio:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT_STG $SSH_USER@$SSH_HOST_STG
  deploystg:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT_STG $SSH_USER_STG@$SSH_HOST_STG
workflows:
  version: 2
  chk-on-stg:
    jobs:
      - deploystg:
          filters:
            branches:
              only: dev
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - deployShinyio:
          filters:
            branches:
              only: master
