name: 表示用データセット作成

on:
  pull_request:
    paths:
    - 50_Data/**/*
    branches: [ master ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  generate:
    needs: label
    name: Data Update
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('data.table', 'sparkline', 'purrr', 'jsonlite', 'reshape2', 'tidyverse', 'lubridate', 'remotes'))"
      - name: Run Script
        run: |
          Rscript -e 'source("00_System/CreateTable.R")'
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: 🙆表示用データセット作成
          ref: ${{ github.head_ref }}
  merge:
    needs: [label, generate]
    name: Auto merge data update pull request
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "data_update"
          MERGE_METHOD: "squash"
